org: upstandfm
app: api
service: standups-api

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.upstand.fm
    basePath: standups
    stage: ${opt:stage, 'prod'}
    createRoute53Record: false
  cors:
    origin: '*'
  authorizer:
    arn: ${secrets:AUTH0_AUTHORIZER_ARN}
    resultTtlInSeconds: 60
    identitySource: method.request.header.Authorization
    # Note that Bearer must be capitalized
    identityValidationExpression: '^Bearer [-0-9a-zA-z\.]*$'
    type: token

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  cfnRole: ${secrets:CFN_ROLE_ARN}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: upstandfm-deployments
    serverSideEncryption: AES256 # when using server-side encryption
  environment:
    CORS_ALLOW_ORIGIN: ${self:custom.cors.origin}
    # The ARN has the format "arn:aws:dynamodb:::table/tableName"
    # Splitting on "/" gives us the name
    DYNAMODB_TABLE_NAME:
      'Fn::Select':
        ['1', { 'Fn::Split': ['/', '${state:infra.standupsTableArn}'] }]
    DYNAMODB_INVERTED_INDEX_NAME: ${state:infra.standupsInvertedIndex}
    DEFAULT_QUERY_LIMIT: 10
    CREATE_STANDUP_SCOPE: 'create:standup'
    READ_STANDUPS_SCOPE: 'read:standups'

  # See: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: ${state:infra.standupsTableArn}
    - Effect: Allow
      Action:
        - dynamodb:Query
      # The ARN has the format "arn:aws:dynamodb:::table/tableName/index/indexName"
      # Joining on "/" gives us the ARN of the index
      Resource:
        'Fn::Join':
          [
            '/',
            [
              '${state:infra.standupsTableArn}',
              'index',
              '${state:infra.standupsInvertedIndex}',
            ],
          ]

package:
  exclude:
    - ./*
    - ./**/*.test.js
  include:
    - node_modules
    - src

functions:
  createStandup:
    handler: src/handler.createStandup
    description: Creates a standup
    events:
      - http:
          method: post
          path: /
          cors: ${self:custom.cors}
          authorizer: ${self:custom.authorizer}
  getStandups:
    handler: src/handler.getStandups
    description: Gets all standups for a user
    events:
      - http:
          method: get
          path: /
          request:
            parameters:
              queryStrings:
                limit: false # optional query param
                cursor: false # optional query param
          cors: ${self:custom.cors}
          authorizer: ${self:custom.authorizer}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
